name:                oniOrHuman
author:              "Cj.bc_sd a.k.a Cj-bc"
maintainer:          "cj.bc-sd@outlook.jp"
copyright:           "MIT"


description:         Shgif control script

dependencies:
- base >= 4.7 && < 5
- vty
- brick
- brick-shgif
- random
- microlens
- microlens-th

executables:
  oniOrHuman:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
