* playground

This is _my_ playground.
There're some practical codes/tools.

** Code quality isn't guaranteed; Do not expect "Good code" here
All codes here are not planned to be maintained. Even I acknoledge
that [[https://github.com/Cj-bc/playground/security/dependabot][dependabot]] have alerted me a lot of problems, I'm not going to
fix them because those codes here aren't used anymore.

* Directory structure
Basically, codes are stored in individual directories based on used language/framework.
So [[haskell]] contains haskell programs, [[go]] contains golang one, and so on.
However, if the program satisfies one of requirements listed below are stored in [[project]] directory:

+ program is composed from several languages (e.g. contains both server-side and client-side)
+ I want to/or plan to write the same program with several other languages(e.g. trying to implement RFC in several languages)

* Some playable programs 

*note: this list is outdated.*

- [[haskell/blackjack/README.md][haskell/blackjack]] :: CUI Black jack program in Haskell
- [[haskell/faceWithShgif/README.md][haskell/faceWithShgif]] :: Control AA face model with keyboard
- [[haskell/oniOrHuman/README.md][haskell/oniOrHuman]] :: Simple CUI timing game
- [[haskell/qotd-hs/README.md][haskell/qotd-hs]] :: Quote of the day server (RFC865)
- [[haskell/echo-server/README.md][haskell/echo-server]] :: Echo server (RFC862)
