name:                hit-n-blow
version:             0.1.0.0
github:              "Cj-bc/hit-n-blow"
license:             BSD3
author:              "Cj.bc_sd a.k.a Cj-bc"
maintainer:          "cj.bc-sd@outlook.jp"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Cj-bc/hit-n-blow#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- transformers
- data-default

library:
  source-dirs: src

executables:
  hit-n-blow-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hit-n-blow

tests:
  hit-n-blow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hit-n-blow
