name:                gi-gtk-declarative-trying
version:             0.1.0.0
github:              "githubuser/gi-gtk-declarative-trying"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gi-gtk-declarative-trying#readme>

dependencies:
- base >= 4.7 && < 5
- gi-gtk
- gi-gtk-declarative
- gi-gtk-declarative-app-simple
- text
- vector
- uuid
- containers
- lens

library:
  source-dirs: src

executables:
  gi-gtk-declarative-trying-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -haddock
    dependencies:
    - gi-gtk-declarative-trying

tests:
  gi-gtk-declarative-trying-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gi-gtk-declarative-trying
