openapi: 3.0.0
paths:
  /todoes:
    get:
      summary: Returns all todoes registered
      responses:
        '200':
          description: List of Todo object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
  /todo/{todo-id}:
    get:
      summary: Returns details of one todo
      responses:
        '200':
          description: Detailed information about the todo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        '404':
          description: Given id isn't exist
        '400':
          description: given `todo-id` was not integer

  patch:
    summary: Update Content of todo
    responses:
      '200':
        description: Update succeed
      '400':
        description: neither "title" nor "isDone" are provided in body
      '500':
        description: Failed to save the change
  /todo:
    post:
      summary: Create new todo


components:
  schemas:
    Todo:
      type: object
      properties:
        title:
          type: string
        isDone:
          type: bool
        id:
          type: string